dict 1 = {1:"python",2:"java",3:"Ruby",4:"scala"}
dict 2 = dict1.copy()
print(dict 2)
dict1.clear()
print(dict1)
print (dict2.get(1))
print (dict2.items())
print (dict2.keys())
dict2.pop(4)
print( dict2)
dict2.pop item()
print(dict2)
dict 2.update ({3:"scala"})
print ( dict 2)
print(dict 2. values())